function writeTemplateFunction(templateStr,templateName,fullFilename)
% WriteTemplateFunction - writes the template function to +Templates.
%
%Usage:
%   -WriteTemplateFunction(templateStr,templateName,fullFilename)
%
%   WARNING! This is a helper function used by higher level functions that
%   do error checking to make sure this file does not break things.  Don't
%   call it explitly!
%
%Inputs:
%   -templateStr:  string containing template text
%   -templateName: name of function file to be called
%   -fullFilename: full path to file name of template
%
%Outputs:
%   -None!
%
%See Also: newTemplateFromCurrentEditor,
%

%
% Copyright 2013 The MathWorks, Inc. 
% SCd - MathWorks 02/04/2013
%

    %Rudimentary Error Checking: don't call this function explictly!
    narginchk(3,3);

    %Write the template shortcut function
    
    %Reopen the file and save it.
    fid = fopen(fullFilename,'w');
    
    %Write the Header information:
    fprintf(fid,'function %s\n%% %s Template Shortcut - Autogenerated %s\n\n',...
        templateName(1:end-2), upper(templateName(1:end-2)), datestr(now));
    
    %Acquire the editor handle and check its validity
    fprintf(fid,'hEditor = matlab.desktop.editor.getActive; %%Active Editor\n');
    fprintf(fid,'if isempty(hEditor)   %%Check Validity\n    edit;\n    hEditor = matlab.desktop.editor.getActive; %%Active Editor\nend\n\n');
    
    %Get the position in the file:
    fprintf(fid,'%%Positional Information:\nposition = hEditor.Selection;\n');
    fprintf(fid,'lineNumber = position(1);\ncolumn  = position(2);\n\n');
    
    %Convert to double so that the contents does not mess up the new file.
    %E.g. we don't want the file to break if they have single quotes or
    %other wierdness.    
    fprintf(fid,'%%Text as a double\ntextLines = [');
    fprintf(fid,'%g ',double(templateStr)); 
    fprintf(fid,'];\n\n');
    
    %Do the insertion:
    fprintf(fid,'%%Insert the text in the editor:\n');    
    fprintf(fid,'insertTextAtPositionInLine(hEditor,char(textLines),lineNumber,column);\n\n');
    
    %End of file!
    fprintf(fid,'end');
        
    %Clean Up
    fclose(fid);

end