function testCovGauss(imSnippet)
    [y,x] = meshgrid(1:size(imSnippet,2), 1:size(imSnippet,1));

    inits = {5, [5, 5], .5, [2, 2], [10, -1, 1]};
    
singleGaussianV2 = @(A, r, rho, sigma, offset) A*exp(-1/(2*(1-rho^2))*(...
        ...
        (x-r(1)).^2/(2*sigma(1)^2) + (y-r(2)).^2/(2*sigma(2)^2) ...
        - 2*rho*(x-r(1)).*(y-r(2)) /  (sigma(1)*sigma(2) )...
        ))...  
        - offset(1) - offset(2)*x - offset(3)*y...
        - double(imSnippet);
    
    inits2 = [5, 5, 5, .5, 2, 2, 10, -1, 1];
    
    sg = @(A, x0, y0, rho, sigma_x, sigma_y, offset, offset_x, offset_y) A*exp(-1/(2*(1-rho^2))*(...
        ...
        (x-x0).^2/(2*sigma_x^2) + (y-y0).^2/(2*sigma_y^2) ...
        - 2*rho*(x-x0).*(y-y0) /  (sigma_x*sigma_y )...
        ))...  
        - offset - offset_x*x - offset_y*y...
        - double(imSnippet);
    
    lsqnonlin(sg, inits2)
end