% abrev.m

BUTTON(    = uicontrol('str',;
RADIO(     = uicontrol('sty','radio','str',;
POPUP(     = uicontrol('sty','pop','str',;
TEXT(      = uicontrol('sty','text','str',;
EDIT(      = uicontrol('sty','edit',;
SLIDER(    = uicontrol('sty','slid',;
SHOWhelp   = 'plt help;';
CLICKhelp  = 'plt help 1;';
CLICKgrid  = 'plt click TGLgrid;';
CLICKhcpy  = 'plt(''hcpy'',''init'',gcf);';
CLICKmenu  = 'plt click TGLmenu;';
CLICKyedit = 'plt click Yedit;';
HIDE       = 'vis','of';
SHOW       = 'vis','on';
ENABLE     = 'ena','on';
DISABLE    = 'ena','of';
INACTIVE   = 'ena','inact';
HANDLEvis  = 'handlev','on';
ITALIC     = 'fonta','ita';
ITALICnot  = 'fonta','nor';
BOLD       = 'fontw','bol';
BOLDnot    = 'fontw','nor';
NORMAL     = 'unit','nor';
PIXELS     = 'unit','pix';
NOTICK     = 'XtickLabel',' ','YtickLabel',' ','TickLen',[0 0]';
POS        = 'pos';
USER       = 'userdata';
TAG        = 'tag';
MOUSE      = 'buttond';
STR        = 'str';
CALLBK     = 'callback';
UICONTEXT  = 'ui';
BACKGROUND = 'backg';
FOREGROUND = 'foreg';
FONTSIZE   = 'fontsi';
LINESTYLE  = 'linest';
VISIBLE    = 'vis';
COLOR      = 'color';
XCOLOR     = 'xcol';
YCOLOR     = 'ycol';
XLABEL     = 'xlab';
YLABEL     = 'ylab';
XLIM       = 'xlim';
YLIM       = 'ylim';
XDATA      = 'x';
YDATA      = 'y';
ZDATA      = 'z';
CurPOINT   = 'currentp';
CHILDREN   = 'child';
PARENT     = 'par';
INVERTHC   = 'invert'; % InvertHardCopy
LEFTalgn   = 'horiz','left';
CENTERalgn = 'horiz','cent';
RIGHTalgn  = 'horiz','right';
YLIMman    = 'YlimM','man';
YLIMauto   = 'YlimM','auto';
NoCUR      = 'tag','SkipCur';
TAGg       = 'tag',get(gcf,'tag');
isGRID     = 'user','grid';
isTraceID  = 'user','TraceID';
VALUE      = 'Val';
vON        = 'Val',1;
vOFF       = 'Val',0;
ClickType  = 'SelectionT';  % type of mouse click
MouseType  = sum(get(gcf,ClickType))
MouseLeft  = MouseType==normal_
MouseRight = MouseType==alt_
MouseDbl   = MouseType==open_
NoMENU     = 'menu','none','numberT','off','back','off';  % No menu, NumberTitle, or BackingStore
MOTIONoff  = 'set(gcf,''WindowButtonMotionFcn'','''',''WindowButtonUpFcn'','''');';
MOTIONOFF  = set(gcf,'WindowButtonMotionFcn','','WindowButtonUpFcn','');
MOTIONstop = 'WindowButtonUpFcn',MOTIONoff;
