function newFun
% NEWFUN Template Shortcut - Autogenerated 15-Feb-2013 11:51:09

%
% Copyright 2013 The MathWorks, Inc. 
%

hEditor = matlab.desktop.editor.getActive; %Active Editor
if isempty(hEditor)   %Check Validity
    edit;
    hEditor = matlab.desktop.editor.getActive; %Active Editor
end

%Positional Information:
position = hEditor.Selection;
lineNumber = position(1);
column  = position(2);

%Text as a double
textLines = [102 117 110 99 116 105 111 110 32 91 93 32 61 32 102 111 111 40 41 10 37 10 37 10 37 85 115 97 103 101 58 10 37 32 32 32 45 10 37 10 37 10 37 73 110 112 117 116 115 58 10 37 32 32 32 45 10 37 10 37 79 117 116 112 117 116 115 58 10 37 32 32 32 45 10 37 10 37 83 101 101 32 65 108 115 111 58 10 37 10 10 10 10 10 10 101 110 100 ];

%Insert the text in the editor:
insertTextAtPositionInLine(hEditor,char(textLines),lineNumber,column);

end