function newListbox
% NEWLISTBOX Template Shortcut - Autogenerated 12-Feb-2013 11:00:57

%
% Copyright 2013 The MathWorks, Inc. 
%

hEditor = matlab.desktop.editor.getActive; %Active Editor
if isempty(hEditor)   %Check Validity
    edit;
    hEditor = matlab.desktop.editor.getActive; %Active Editor
end

%Positional Information:
position = hEditor.Selection;
lineNumber = position(1);
column  = position(2);

%Text as a double
textLines = [117 105 99 111 110 116 114 111 108 40 39 83 116 121 108 101 39 44 39 108 105 115 116 98 111 120 39 44 46 46 46 10 32 32 32 32 32 32 32 32 32 32 39 85 110 105 116 115 39 44 39 110 111 114 109 97 108 105 122 101 100 39 44 46 46 46 10 32 32 32 32 32 32 32 32 32 32 39 80 111 115 105 116 105 111 110 39 44 91 48 46 49 32 48 46 49 32 48 46 51 32 48 46 53 93 44 46 46 46 10 32 32 32 32 32 32 32 32 32 32 39 83 116 114 105 110 103 39 44 123 39 72 101 108 108 111 32 87 111 114 108 100 39 125 44 46 46 46 10 32 32 32 32 32 32 32 32 32 32 39 77 97 120 39 44 49 44 46 46 46 32 37 73 110 99 114 101 97 115 101 32 102 111 114 32 109 117 108 116 105 115 101 108 101 99 116 10 32 32 32 32 32 32 32 32 32 32 39 86 97 108 117 101 39 44 49 44 46 46 46 10 32 32 32 32 32 32 32 32 32 32 39 67 97 108 108 98 97 99 107 39 44 91 93 41 59 10 32 32 32 32 32 32 32 32 32 32 32 10 ];

%Insert the text in the editor:
insertTextAtPositionInLine(hEditor,char(textLines),lineNumber,column);

end