function tmwcopywrite
% TMWCOPYWRITE Template Shortcut - Autogenerated 25-Feb-2013 16:12:22

%
% Copyright 2013 The MathWorks, Inc. 
%

hEditor = matlab.desktop.editor.getActive; %Active Editor
if isempty(hEditor)   %Check Validity
    edit;
    hEditor = matlab.desktop.editor.getActive; %Active Editor
end

%Positional Information:
position = hEditor.Selection;
lineNumber = position(1);
column  = position(2);

%Text as a double
textLines = [37 32 32 32 67 111 112 121 114 105 103 104 116 32 50 48 49 51 32 84 104 101 32 77 97 116 104 87 111 114 107 115 44 32 73 110 99 46 32 10 ];

%Insert the text in the editor:
insertTextAtPositionInLine(hEditor,char(textLines),lineNumber,column);

end