params = {'where', 'Submit', 'datafile', '','query','a','matfile', '',...
    'matrix', '', 'b', '', 'C', '0','A', 'a%3At+c%3Ag',...
    'alpha', '1', 'd', 'd1', 'l', '', 'u', '', 'R', '10000',...
    'M', '0', 'output', 'Display+on+screen', '.cgifields', 'e',...
    '.cgifields', 't', '.cgifields', 'output', '.cgifields', 'S',...
    '.cgifields', 'v', '.cgifields', 'p', '.cgifields', 'w'};
params = {};
s = urlread('http://stormo.wustl.edu/consensus/cgi-bin/Server/Interface/patser.cgi', 'Post', params);
%urlread('C:\Users\ArmandoReimer\Desktop\patsercgi.html', 'Post', params)
%web('C:\Users\ArmandoReimer\Desktop\patsercgi.html', '-browser')